
 	subroutine populate_bfm_strings

 	! set up strings for BFM

 	use shyfem_strings

 	implicit none

	call strings_add_new('Oxygen [mmol O2/m3]', 601)
	call strings_add_new('Phosphate (PO4) [mmol P/m3]', 602)
	call strings_add_new('Nitrate (NoX) [mmol N/m3]', 603)
	call strings_add_new('Ammonium (NH4) [mmol N/m3]', 604)
	call strings_add_new('NitrogenSink [mmol N/m3]', 605)
	call strings_add_new('Silicate [mmol Si/m3]', 606)
	call strings_add_new('Reduction Equivalents [mmol S--/m3]', 607)
	call strings_add_new('Aerobic and Anaerobic Bacteria C [mg C/m3]', 608)
	call strings_add_new('Aerobic and Anaerobic Bacteria N [mmol N/m3]', 609)
	call strings_add_new('Aerobic and Anaerobic Bacteria P [mmol P/m3]', 610)
	call strings_add_new('Diatoms C [mg C/m3]', 611)
	call strings_add_new('Diatoms N [mmol N/m3]', 612)
	call strings_add_new('Diatoms P [mmol P/m3]', 613)
	call strings_add_new('Diatoms Chl [mg Chl/m3]', 614)
	call strings_add_new('Diatoms Si [mmol Si/m3]', 615)
	call strings_add_new('Flagellates C [mg C/m3]', 616)
	call strings_add_new('Flagellates N [mmol N/m3]', 617)
	call strings_add_new('Flagellates P [mmol P/m3]', 618)
	call strings_add_new('Flagellates Chl [mg Chl/m3]', 619)
	call strings_add_new('PicoPhytoplankton C [mg C/m3]', 620)
	call strings_add_new('PicoPhytoplankton N [mmol N/m3]', 621)
	call strings_add_new('PicoPhytoplankton P [mmol P/m3]', 622)
	call strings_add_new('PicoPhytoplankton Chl [mg Chl/m3]', 623)
	call strings_add_new('Large Phytoplankton C [mg C/m3]', 624)
	call strings_add_new('Large Phytoplankton N [mmol N/m3]', 625)
	call strings_add_new('Large Phytoplankton P [mmol P/m3]', 626)
	call strings_add_new('Large Phytoplankton Chl [mg Chl/m3]', 627)
	call strings_add_new('Carnivorous Mesozooplankton C [mg C/m3]', 628)
	call strings_add_new('Carnivorous Mesozooplankton N [mmol N/m3]', 629)
	call strings_add_new('Carnivorous Mesozooplankton P [mmol P/m3]', 630)
	call strings_add_new('Omnivorous Mesozooplankton C [mg C/m3]', 631)
	call strings_add_new('Omnivorous Mesozooplankton N [mmol N/m3]', 632)
	call strings_add_new('Omnivorous Mesozooplankton P [mmol P/m3]', 633)
	call strings_add_new('Microzooplankton C [mg C/m3]', 634)
	call strings_add_new('Microzooplankton N [mmol N/m3]', 635)
	call strings_add_new('Microzooplankton P [mmol P/m3]', 636)
	call strings_add_new('Heterotrophic Nanoflagellates (HNAN) C [mg C/m3]', 637)
	call strings_add_new('Heterotrophic Nanoflagellates (HNAN) N [mmol N/m3]', 638)
	call strings_add_new('Heterotrophic Nanoflagellates (HNAN) P [mmol P/m3]', 639)
	call strings_add_new('Labile Dissolved Organic Matter C [mg C/m3]', 640)
	call strings_add_new('Labile Dissolved Organic Matter N [mmol N/m3]', 641)
	call strings_add_new('Labile Dissolved Organic Matter P [mmol P/m3]', 642)
	call strings_add_new('Labile Dissolved Organic Matter (cromophoric) [mg C/m3]', 643)
	call strings_add_new('Semi-labile Dissolved Organic Carbon [mg C/m3]', 644)
	call strings_add_new('Semi-labile Dissolved Organic Carbon (cromophoric) [mg C/m3]', 645)
	call strings_add_new('Semi-refractory Dissolved Organic Carbon [mg C/m3]', 646)
	call strings_add_new('Semi-refractory Dissolved Organic Carbon (cromophoric) [mg C/m3]', 647)
	call strings_add_new('Particulate Organic Matter C [mg C/m3]', 648)
	call strings_add_new('Particulate Organic Matter N [mmol N/m3]', 649)
	call strings_add_new('Particulate Organic Matter P [mmol P/m3]', 650)
	call strings_add_new('Particulate Organic Matter Si [mmol Si/m3]', 651)
	call strings_add_new('Dissolved Inorganic Carbon C [mg C/m3]', 652)
	call strings_add_new('Dissolved Inorganic Carbon eq [mmol eq/m3]', 653)
	call strings_add_new('Calcite [mg C/m3]', 654)

	call strings_set_short( 601,'bfm_O2o')
	call strings_set_short( 602,'bfm_N1p')
	call strings_set_short( 603,'bfm_N3n')
	call strings_set_short( 604,'bfm_N4n')
	call strings_set_short( 605,'bfm_O4n')
	call strings_set_short( 606,'bfm_N5s')
	call strings_set_short( 607,'bfm_N6r')
	call strings_set_short( 608,'bfm_B1c')
	call strings_set_short( 609,'bfm_B1n')
	call strings_set_short( 610,'bfm_B1p')
	call strings_set_short( 611,'bfm_P1c')
	call strings_set_short( 612,'bfm_P1n')
	call strings_set_short( 613,'bfm_P1p')
	call strings_set_short( 614,'bfm_P1l')
	call strings_set_short( 615,'bfm_P1s')
	call strings_set_short( 616,'bfm_P2c')
	call strings_set_short( 617,'bfm_P2n')
	call strings_set_short( 618,'bfm_P2p')
	call strings_set_short( 619,'bfm_P2l')
	call strings_set_short( 620,'bfm_P3c')
	call strings_set_short( 621,'bfm_P3n')
	call strings_set_short( 622,'bfm_P3p')
	call strings_set_short( 623,'bfm_P3l')
	call strings_set_short( 624,'bfm_P4c')
	call strings_set_short( 625,'bfm_P4n')
	call strings_set_short( 626,'bfm_P4p')
	call strings_set_short( 627,'bfm_P4l')
	call strings_set_short( 628,'bfm_Z3c')
	call strings_set_short( 629,'bfm_Z3n')
	call strings_set_short( 630,'bfm_Z3p')
	call strings_set_short( 631,'bfm_Z4c')
	call strings_set_short( 632,'bfm_Z4n')
	call strings_set_short( 633,'bfm_Z4p')
	call strings_set_short( 634,'bfm_Z5c')
	call strings_set_short( 635,'bfm_Z5n')
	call strings_set_short( 636,'bfm_Z5p')
	call strings_set_short( 637,'bfm_Z6c')
	call strings_set_short( 638,'bfm_Z6n')
	call strings_set_short( 639,'bfm_Z6p')
	call strings_set_short( 640,'bfm_R1c')
	call strings_set_short( 641,'bfm_R1n')
	call strings_set_short( 642,'bfm_R1p')
	call strings_set_short( 643,'bfm_R1l')
	call strings_set_short( 644,'bfm_R2c')
	call strings_set_short( 645,'bfm_R2l')
	call strings_set_short( 646,'bfm_R3c')
	call strings_set_short( 647,'bfm_R3l')
	call strings_set_short( 648,'bfm_R6c')
	call strings_set_short( 649,'bfm_R6n')
	call strings_set_short( 650,'bfm_R6p')
	call strings_set_short( 651,'bfm_R6s')
	call strings_set_short( 652,'bfm_O3c')
	call strings_set_short( 653,'bfm_O3h')
	call strings_set_short( 654,'bfm_O5c')

 	end subroutine

