
 	subroutine populate_strings_cbms

 	! set up strings for cbms

 	use shyfem_strings

 	implicit none

	call strings_add_new('cbms Oxygen [mmol O2/m3]',1001)
	call strings_add_new('cbms Phosphate (PO4) [mmol P/m3]',1002)
	call strings_add_new('cbms Nitrate (NoX) [mmol N/m3]',1003)
	call strings_add_new('cbms Ammonium (NH4) [mmol N/m3]',1004)
	call strings_add_new('cbms NitrogenSink [mmol N/m3]',1005)
	call strings_add_new('cbms Silicate [mmol Si/m3]',1006)
	call strings_add_new('cbms Reduction Equivalents [mmol S--/m3]',1007)
	call strings_add_new('cbms Aerobic and Anaerobic Bacteria C [mg C/m3]',1008)
	call strings_add_new('cbms Aerobic and Anaerobic Bacteria N [mmol N/m3]',1009)
	call strings_add_new('cbms Aerobic and Anaerobic Bacteria P [mmol P/m3]',1010)
	call strings_add_new('cbms Diatoms C [mg C/m3]',1011)
	call strings_add_new('cbms Diatoms N [mmol N/m3]',1012)
	call strings_add_new('cbms Diatoms P [mmol P/m3]',1013)
	call strings_add_new('cbms Diatoms Chl [mg Chl/m3]',1014)
	call strings_add_new('cbms Diatoms Si [mmol Si/m3]',1015)
	call strings_add_new('cbms Flagellates C [mg C/m3]',1016)
	call strings_add_new('cbms Flagellates N [mmol N/m3]',1017)
	call strings_add_new('cbms Flagellates P [mmol P/m3]',1018)
	call strings_add_new('cbms Flagellates Chl [mg Chl/m3]',1019)
	call strings_add_new('cbms PicoPhytoplankton C [mg C/m3]',1020)
	call strings_add_new('cbms PicoPhytoplankton N [mmol N/m3]',1021)
	call strings_add_new('cbms PicoPhytoplankton P [mmol P/m3]',1022)
	call strings_add_new('cbms PicoPhytoplankton Chl [mg Chl/m3]',1023)
	call strings_add_new('cbms Large Phytoplankton C [mg C/m3]',1024)
	call strings_add_new('cbms Large Phytoplankton N [mmol N/m3]',1025)
	call strings_add_new('cbms Large Phytoplankton P [mmol P/m3]',1026)
	call strings_add_new('cbms Large Phytoplankton Chl [mg Chl/m3]',1027)
	call strings_add_new('cbms Carnivorous Mesozooplankton C [mg C/m3]',1028)
	call strings_add_new('cbms Carnivorous Mesozooplankton N [mmol N/m3]',1029)
	call strings_add_new('cbms Carnivorous Mesozooplankton P [mmol P/m3]',1030)
	call strings_add_new('cbms Omnivorous Mesozooplankton C [mg C/m3]',1031)
	call strings_add_new('cbms Omnivorous Mesozooplankton N [mmol N/m3]',1032)
	call strings_add_new('cbms Omnivorous Mesozooplankton P [mmol P/m3]',1033)
	call strings_add_new('cbms Microzooplankton C [mg C/m3]',1034)
	call strings_add_new('cbms Microzooplankton N [mmol N/m3]',1035)
	call strings_add_new('cbms Microzooplankton P [mmol P/m3]',1036)
	call strings_add_new('cbms Heterotrophic Nanoflagellates (HNAN) C [mg C/m3]',1037)
	call strings_add_new('cbms Heterotrophic Nanoflagellates (HNAN) N [mmol N/m3]',1038)
	call strings_add_new('cbms Heterotrophic Nanoflagellates (HNAN) P [mmol P/m3]',1039)
	call strings_add_new('cbms Labile Dissolved Organic Matter C [mg C/m3]',1040)
	call strings_add_new('cbms Labile Dissolved Organic Matter N [mmol N/m3]',1041)
	call strings_add_new('cbms Labile Dissolved Organic Matter P [mmol P/m3]',1042)
	call strings_add_new('cbms Labile Dissolved Organic Matter (cromophoric) [mg C/m3]',1043)
	call strings_add_new('cbms Semi-labile Dissolved Organic Carbon [mg C/m3]',1044)
	call strings_add_new('cbms Semi-labile Dissolved Organic Carbon (cromophoric) [mg C/m3]',1045)
	call strings_add_new('cbms Semi-refractory Dissolved Organic Carbon [mg C/m3]',1046)
	call strings_add_new('cbms Semi-refractory Dissolved Organic Carbon (cromophoric) [mg C/m3]',1047)
	call strings_add_new('cbms Particulate Organic Matter C [mg C/m3]',1048)
	call strings_add_new('cbms Particulate Organic Matter N [mmol N/m3]',1049)
	call strings_add_new('cbms Particulate Organic Matter P [mmol P/m3]',1050)
	call strings_add_new('cbms Particulate Organic Matter Si [mmol Si/m3]',1051)
	call strings_add_new('cbms Dissolved Inorganic Carbon C [mg C/m3]',1052)
	call strings_add_new('cbms Dissolved Inorganic Carbon eq [mmol eq/m3]',1053)
	call strings_add_new('cbms Calcite [mg C/m3]',1054)
	call strings_add_new('cbms bfm diag ppqpcPPY_iiP1 phosphorus quota P1 [mmolP/mgC]',1151)
	call strings_add_new('cbms bfm diag ppqpcPPY_iiP2 phosphorus quota P2 [mmolP/mgC]',1152)
	call strings_add_new('cbms bfm diag ppqpcPPY_iiP3 phosphorus quota P3 [mmolP/mgC]',1153)
	call strings_add_new('cbms bfm diag ppqpcPPY_iiP4 phosphorus quota P4 [mmolP/mgC]',1154)
	call strings_add_new('cbms bfm diag ppqncPPY_iiP1 nitrogen quota P1 [mmolN/mgC]',1155)
	call strings_add_new('cbms bfm diag ppqncPPY_iiP2 nitrogen quota P2 [mmolN/mgC]',1156)
	call strings_add_new('cbms bfm diag ppqncPPY_iiP3 nitrogen quota P3 [mmolN/mgC]',1157)
	call strings_add_new('cbms bfm diag ppqncPPY_iiP4 nitrogen quota P4 [mmolN/mgC]',1158)
	call strings_add_new('cbms bfm diag ppqscPPY_iiP1 silicon quota [mmolS/mgC]',1159)
	call strings_add_new('cbms bfm diag ppeiPPY_iiP1 light limitation P1 [adimensional]',1160)
	call strings_add_new('cbms bfm diag ppeiPPY_iiP2 light limitation P2 [adimensional]',1161)
	call strings_add_new('cbms bfm diag ppeiPPY_iiP3 light limitation P3 [adimensional]',1162)
	call strings_add_new('cbms bfm diag ppeiPPY_iiP4 light limitation P4 [adimensional]',1163)
	call strings_add_new('cbms bfm diag ppuc_iiP1 carbon correction [mgC/m3/d]',1164)
	call strings_add_new('cbms bfm diag ppuc_iiP2',1165)
	call strings_add_new('cbms bfm diag ppuc_iiP3',1166)
	call strings_add_new('cbms bfm diag ppuc_iiP4',1167)
	call strings_add_new('cbms bfm diag ppun_iiP1',1168)
	call strings_add_new('cbms bfm diag ppun_iiP2',1169)
	call strings_add_new('cbms bfm diag ppun_iiP3',1170)
	call strings_add_new('cbms bfm diag ppun_iiP4',1171)
	call strings_add_new('cbms bfm diag ppup_iiP1',1172)
	call strings_add_new('cbms bfm diag ppup_iiP2',1173)
	call strings_add_new('cbms bfm diag ppup_iiP3',1174)
	call strings_add_new('cbms bfm diag ppup_iiP4',1175)
	call strings_add_new('cbms bfm diag ppETW Temperature [deg Celsius]',1176)
	call strings_add_new('cbms bfm diag ppESW Salinity',1177)
	call strings_add_new('cbms bfm diag ppERHO Density',1178)
	call strings_add_new('cbms bfm diag ppPAR_phyto1',1179)
	call strings_add_new('cbms bfm diag ppruPPYc Gross Primary production',1180)
	call strings_add_new('cbms bfm diag ppresPPYc Phytoplankton respiration',1181)
	call strings_add_new('cbms bfm diag ppruZOOc Predation',1182)
	call strings_add_new('cbms bfm diag ppremPBAn Bacterial remineralization',1183)
	call strings_add_new('cbms bfm diag ppremPBAp Bacterial remineralization',1184)
	call strings_add_new('cbms bfm diag ppremPOC POC remineralization',1185)
	call strings_add_new('cbms bfm diag pppH pH',1186)
	call strings_add_new('cbms bfm diag ppruPBAc uptake and grazing',1187)
	call strings_add_new('cbms bfm diag ppruMEZ1c uptake and grazing',1188)
	call strings_add_new('cbms bfm diag ppruMEZ2c uptake and grazing',1189)
	call strings_add_new('cbms bfm diag ppruMIZ1c uptake and grazing',1190)
	call strings_add_new('cbms bfm diag ppruMIZ2c uptake and grazing',1191)
	call strings_add_new('cbms benthic Oxygen [mmol O2/m3]',1301)
	call strings_add_new('cbms benthic Phosphate (PO4) [mmol P/m3]',1302)
	call strings_add_new('cbms benthic Nitrate (NoX) [mmol N/m3]',1303)
	call strings_add_new('cbms benthic Ammonium (NH4) [mmol N/m3]',1304)
	call strings_add_new('cbms benthic Silicate [mmol Si/m3]',1305)
	call strings_add_new('cbms benthic Dissolved Inorganic Carbon [mg C/m3]',1306)
	call strings_add_new('cbms benthic Particulate Organic Matter C [mg C/m3]',1307)
	call strings_add_new('cbms benthic Particulate Organic Matter N [mmol N/m3]',1308)
	call strings_add_new('cbms benthic Particulate Organic Matter P [mmol P/m3]',1309)
	call strings_add_new('cbms benthic Particulate Organic Matter Si [mmol Si/m3]',1310)
	call strings_add_new('cbms benthic Labile Dissolved Organic Matter C [mg C/m3]',1311)
	call strings_add_new('cbms benthic Labile Dissolved Organic Matter N [mmol N/m3]',1312)
	call strings_add_new('cbms benthic Labile Dissolved Organic Matter P [mmol P/m3]',1313)
	call strings_add_new('cbms benthic diffusion of Oxygen O2 [mmol O2/m3]',1401)
	call strings_add_new('cbms benthic diffusion of Phosphate (PO4) P [mmol P/m3]',1402)
	call strings_add_new('cbms benthic diffusion of Nitrate (NoX) N [mmol N/m3]',1403)
	call strings_add_new('cbms benthic diffusion of Ammonium (NH4) N [mmol N/m3]',1404)
	call strings_add_new('cbms benthic diffusion of Silicate Si [mmol Si/m3]',1405)
	call strings_add_new('cbms benthic diffusion of Dissolved Inorganic Carbon C [mg C/m3]',1406)
	call strings_add_new('cbms benthic diffusion of Particulate Org. Mat. C [mg C/m3]',1407)
	call strings_add_new('cbms benthic diffusion of Particulate Org. Mat. N [mmol N/m3]',1408)
	call strings_add_new('cbms benthic diffusion of Particulate Org. Mat. P [mmol P/m3]',1409)
	call strings_add_new('cbms benthic diffusion of Particulate Org. Mat. Si [mmol Si/m3]',1410)
	call strings_add_new('cbms benthic diffusion of Labile Dissolved Org. Mat. C [mg C/m3]',1411)
	call strings_add_new('cbms benthic diffusion of Labile Dissolved Org. Mat. N [mmol N/m3]',1412)
	call strings_add_new('cbms benthic diffusion of Labile Dissolved Org. Mat. P [mmol P/m3]',1413)
	call strings_add_new('cbms benthic remineralisation of Oxygen [mmol O2/m3]',1501)
	call strings_add_new('cbms benthic remineralisation of Phosphate (PO4) [mmol P/m3]',1502)
	call strings_add_new('cbms benthic remineralisation of Nitrate (NoX) [mmol N/m3]',1503)
	call strings_add_new('cbms benthic remineralisation of Ammonium (NH4) [mmol N/m3]',1504)
	call strings_add_new('cbms benthic remineralisation of Silicate [mmol Si/m3]',1505)
	call strings_add_new('cbms benthic remineralisation of Dissolved Inorganic Carbon C [mg C/m3]',1506)
	call strings_add_new('cbms benthic remineralisation of Particulate Org. Mat. C [mg C/m3]',1507)
	call strings_add_new('cbms benthic remineralisation of Particulate Org. Mat. N [mmol N/m3]',1508)
	call strings_add_new('cbms benthic remineralisation of Particulate Org. Mat. P [mmol P/m3]',1509)
	call strings_add_new('cbms benthic remineralisation of Particulate Org. Mat. Si [mmol Si/m3]',1510)
	call strings_add_new('cbms benthic remineralisation of Labile Dissolved Org. Mat. C [mg C/m3]',1511)
	call strings_add_new('cbms benthic remineralisation of Labile Dissolved Org. Mat. N [mmol N/m3]',1512)
	call strings_add_new('cbms benthic remineralisation of Labile Dissolved Org. Mat. P [mmol P/m3]',1513)
	call strings_add_new('cbms benthic nitrification of Oxygen O2 [mmol O2/m3]',1601)
	call strings_add_new('cbms benthic nitrification of Phosphate (PO4) P [mmol P/m3]',1602)
	call strings_add_new('cbms benthic nitrification of Nitrate (NoX) N [mmol N/m3]',1603)
	call strings_add_new('cbms benthic nitrification of Ammonium (NH4) N [mmol N/m3]',1604)
	call strings_add_new('cbms benthic nitrification of Silicate Si [mmol Si/m3]',1605)
	call strings_add_new('cbms benthic nitrification of Dissolved Inorganic Carbon C [mg C/m3]',1606)
	call strings_add_new('cbms benthic nitrification of Particulate Org. Mat. C [mg C/m3]',1607)
	call strings_add_new('cbms benthic nitrification of Particulate Org. Mat. N [mmol N/m3]',1608)
	call strings_add_new('cbms benthic nitrification of Particulate Org. Mat. P [mmol P/m3]',1609)
	call strings_add_new('cbms benthic nitrification of Particulate Org. Mat. Si [mmol Si/m3]',1610)
	call strings_add_new('cbms benthic nitrification of Labile Dissolved Org. Mat. C [mg C/m3]',1611)
	call strings_add_new('cbms benthic nitrification of Labile Dissolved Org. Mat. N [mmol N/m3]',1612)
	call strings_add_new('cbms benthic nitrification of Labile Dissolved Org. Mat. P [mmol P/m3]',1613)
	call strings_add_new('cbms benthic denitrification of Oxygen O2 [mmol O2/m3]',1701)
	call strings_add_new('cbms benthic denitrification of Phosphate (PO4) P [mmol P/m3]',1702)
	call strings_add_new('cbms benthic denitrification of Nitrate (NoX) N [mmol N/m3]',1703)
	call strings_add_new('cbms benthic denitrification of Ammonium (NH4) N [mmol N/m3]',1704)
	call strings_add_new('cbms benthic denitrification of Silicate Si [mmol Si/m3]',1705)
	call strings_add_new('cbms benthic denitrification of Dissolved Inorganic Carbon C [mg C/m3]',1706)
	call strings_add_new('cbms benthic denitrification of Particulate Org. Mat. C [mg C/m3]',1707)
	call strings_add_new('cbms benthic denitrification of Particulate Org. Mat. N [mmol N/m3]',1708)
	call strings_add_new('cbms benthic denitrification of Particulate Org. Mat. P [mmol P/m3]',1709)
	call strings_add_new('cbms benthic denitrification of Particulate Org. Mat. Si [mmol Si/m3]',1710)
	call strings_add_new('cbms benthic denitrification of Labile Dissolved Org. Mat. C [mg C/m3]',1711)
	call strings_add_new('cbms benthic denitrification of Labile Dissolved Org. Mat. N [mmol N/m3]',1712)
	call strings_add_new('cbms benthic denitrification of Labile Dissolved Org. Mat. P [mmol P/m3]',1713)
	call strings_add_new('cbms water-benthic diffusion of Oxygen O2 [mmol O2/m3]',1801)
	call strings_add_new('cbms water-benthic diffusion of Phosphate (PO4) P [mmol P/m3]',1802)
	call strings_add_new('cbms water-benthic diffusion of Nitrate (NoX) N [mmol N/m3]',1803)
	call strings_add_new('cbms water-benthic diffusion of Ammonium (NH4) N [mmol N/m3]',1804)
	call strings_add_new('cbms water-benthic diffusion of Silicate Si [mmol Si/m3]',1805)
	call strings_add_new('cbms water-benthic diffusion of Dissolved Inorganic Carbon C [mg C/m3]',1806)
	call strings_add_new('cbms water-benthic diffusion of Particulate Org. Mat. C [mg C/m3]',1807)
	call strings_add_new('cbms water-benthic diffusion of Particulate Org. Mat. N [mmol N/m3]',1808)
	call strings_add_new('cbms water-benthic diffusion of Particulate Org. Mat. P [mmol P/m3]',1809)
	call strings_add_new('cbms water-benthic diffusion of Particulate Org. Mat. Si [mmol Si/m3]',1810)
	call strings_add_new('cbms water-benthic diffusion of Labile Dissolved Org. Mat. C [mg C/m3]',1811)
	call strings_add_new('cbms water-benthic diffusion of Labile Dissolved Org. Mat. N [mmol N/m3]',1812)
	call strings_add_new('cbms water-benthic diffusion of Labile Dissolved Org. Mat. P [mmol P/m3]',1813)
	call strings_add_new('cbms water-benthic deposition of Oxygen O2 [mmol O2/m3]',1901)
	call strings_add_new('cbms water-benthic deposition of Phosphate (PO4) P [mmol P/m3]',1902)
	call strings_add_new('cbms water-benthic deposition of Nitrate (NoX) N [mmol N/m3]',1903)
	call strings_add_new('cbms water-benthic deposition of Ammonium (NH4) N [mmol N/m3]',1904)
	call strings_add_new('cbms water-benthic deposition of Silicate Si [mmol Si/m3]',1905)
	call strings_add_new('cbms water-benthic deposition of Dissolved Inorganic Carbon C [mg C/m3]',1906)
	call strings_add_new('cbms water-benthic deposition of Particulate Org. Mat. C [mg C/m3]',1907)
	call strings_add_new('cbms water-benthic deposition of Particulate Org. Mat. N [mmol N/m3]',1908)
	call strings_add_new('cbms water-benthic deposition of Particulate Org. Mat. P [mmol P/m3]',1909)
	call strings_add_new('cbms water-benthic deposition of Particulate Org. Mat. Si [mmol Si/m3]',1910)
	call strings_add_new('cbms water-benthic deposition of Labile Dissolved Org. Mat. C [mg C/m3]',1911)
	call strings_add_new('cbms water-benthic deposition of Labile Dissolved Org. Mat. N [mmol N/m3]',1912)
	call strings_add_new('cbms water-benthic deposition of Labile Dissolved Org. Mat. P [mmol P/m3]',1913)
	call strings_add_new('cbms water-benthic resuspension of Oxygen O2 [mmol O2/m3]',2001)
	call strings_add_new('cbms water-benthic resuspension of Phosphate (PO4) P [mmol P/m3]',2002)
	call strings_add_new('cbms water-benthic resuspension of Nitrate (NoX) N [mmol N/m3]',2003)
	call strings_add_new('cbms water-benthic resuspension of Ammonium (NH4) N [mmol N/m3]',2004)
	call strings_add_new('cbms water-benthic resuspension of Silicate Si [mmol Si/m3]',2005)
	call strings_add_new('cbms water-benthic resuspension of Dissolved Inorganic Carbon C [mg C/m3]',2006)
	call strings_add_new('cbms water-benthic resuspension of Particulate Org. Mat. C [mg C/m3]',2007)
	call strings_add_new('cbms water-benthic resuspension of Particulate Org. Mat. N [mmol N/m3]',2008)
	call strings_add_new('cbms water-benthic resuspension of Particulate Org. Mat. P [mmol P/m3]',2009)
	call strings_add_new('cbms water-benthic resuspension of Particulate Org. Mat. Si [mmol Si/m3]',2010)
	call strings_add_new('cbms water-benthic resuspension of Labile Dissolved Org. Mat. C [mg C/m3]',2011)
	call strings_add_new('cbms water-benthic resuspension of Labile Dissolved Org. Mat. N [mmol N/m3]',2012)
	call strings_add_new('cbms water-benthic resuspension of Labile Dissolved Org. Mat. P [mmol P/m3]',2013)
	call strings_add_new('cbms water-benthic errosion of Oxygen O2 [mmol O2/m3]',2101)
	call strings_add_new('cbms water-benthic errosion of Phosphate (PO4) P [mmol P/m3]',2102)
	call strings_add_new('cbms water-benthic errosion of Nitrate (NoX) N [mmol N/m3]',2103)
	call strings_add_new('cbms water-benthic errosion of Ammonium (NH4) N [mmol N/m3]',2104)
	call strings_add_new('cbms water-benthic errosion of Silicate Si [mmol Si/m3]',2105)
	call strings_add_new('cbms water-benthic errosion of Dissolved Inorganic Carbon C [mg C/m3]',2106)
	call strings_add_new('cbms water-benthic errosion of Particulate Org. Mat. C [mg C/m3]',2107)
	call strings_add_new('cbms water-benthic errosion of Particulate Org. Mat. N [mmol N/m3]',2108)
	call strings_add_new('cbms water-benthic errosion of Particulate Org. Mat. P [mmol P/m3]',2109)
	call strings_add_new('cbms water-benthic errosion of Particulate Org. Mat. Si [mmol Si/m3]',2110)
	call strings_add_new('cbms water-benthic errosion of Labile Dissolved Org. Mat. C [mg C/m3]',2111)
	call strings_add_new('cbms water-benthic errosion of Labile Dissolved Org. Mat. N [mmol N/m3]',2112)
	call strings_add_new('cbms water-benthic errosion of Labile Dissolved Org. Mat. P [mmol P/m3]',2113)
	call strings_add_new('cbms vma BM',2201)
	call strings_add_new('cbms vma Hcanopy',2202)
	call strings_add_new('cbms vma dBM_dt_Growth',2203)
	call strings_add_new('cbms vma dBM_dt_Mort',2204)
	call strings_add_new('cbms vma Growth',2205)
	call strings_add_new('cbms vma Mortality',2206)
	call strings_add_new('cbms vma Lim_Nitrogen',2207)
	call strings_add_new('cbms vma Lim_Phosphorus',2208)
	call strings_add_new('cbms vma Lim_Salinity',2209)
	call strings_add_new('cbms vma Lim_Temperature',2210)
	call strings_add_new('cbms vma Lim_Light',2211)
	call strings_add_new('cbms vma QN',2212)
	call strings_add_new('cbms vma QP',2213)
	call strings_add_new('cbms vma O2o Oxygen [mmol O2/m3]',2250)
	call strings_add_new('cbms vma N1p Phosphate (PO4) [mmol P/m3]',2251)
	call strings_add_new('cbms vma N3n Nitrate (NoX) [mmol N/m3]',2252)
	call strings_add_new('cbms vma N4n Ammonium (NH4) [mmol N/m3]',2253)
	call strings_add_new('cbms vma R1n Labile Dissolved Org. Mat. [mmol N/m3]',2254)
	call strings_add_new('cbms vma R1c Labile Dissolved Org. Mat. [mg C/m3]',2255)
	call strings_add_new('cbms vma R1p Labile Dissolved Org. Mat. [mmol P/m3]',2256)
	call strings_add_new('cbms vma R6c Particulate Org. Mat. [mg C/m3]',2257)
	call strings_add_new('cbms vma R6n Particulate Org. Mat. [mmol N/m3]',2258)
	call strings_add_new('cbms vma R6p Particulate Org. Mat. [mmol P/m3]',2259)
	call strings_add_new('cbms vma O3c Dissolved Inorganic Carbon [mg C/m3]',2260)
	call strings_add_new('cbms vma Wat_N4n_Uptake',2301)
	call strings_add_new('cbms vma Wat_N3n_Uptake',2302)
	call strings_add_new('cbms vma Wat_R6n_Release',2303)
	call strings_add_new('cbms vma Wat_R1n_Release',2304)
	call strings_add_new('cbms vma Wat_N3n_Release',2305)
	call strings_add_new('cbms vma Wat_N4n_Release',2306)
	call strings_add_new('cbms vma Wat_N1p_Uptake',2307)
	call strings_add_new('cbms vma Wat_N1p_Release',2308)
	call strings_add_new('cbms vma Wat_R6p_Release',2309)
	call strings_add_new('cbms vma Wat_R1p_Release',2310)
	call strings_add_new('cbms vma Wat_O2o_Photosynt',2311)
	call strings_add_new('cbms vma Wat_O2o_Resp',2312)
	call strings_add_new('cbms vma Wat_O3c_Uptake',2313)
	call strings_add_new('cbms vma Wat_O3c_Release',2314)
	call strings_add_new('cbms vma Wat_R6c_Release',2315)
	call strings_add_new('cbms vma Wat_R1c_Release',2316)
	call strings_add_new('cbms water temperature',2401)
	call strings_add_new('cbms water salinity',2402)
	call strings_add_new('cbms water density',2403)
	call strings_add_new('cbms water pH',2404)
	call strings_add_new('cbms water viscosity',2405)
	call strings_add_new('cbms water volume',2406)
	call strings_add_new('cbms area (m2)',2407)
	call strings_add_new('cbms layer thickness',2408)
	call strings_add_new('cbms light',2409)
	call strings_add_new('cbms PAR',2410)
	call strings_add_new('cbms incoming solar radiation',2411)
	call strings_add_new('cbms air temperature (deg C)',2412)
	call strings_add_new('cbms sea surface height (m)',2413)
	call strings_add_new('cbms bottom stress at depth',2414)
	call strings_add_new('cbms wind speed on surface',2415)
	call strings_add_new('cbms water column height',2416)
	call strings_add_new('cbms bottom temperature',2417)
	call strings_add_new('cbms ice cover (0-1)',2418)
	call strings_add_new('cbms air CO2 concentration',2419)
	call strings_add_new('cbms day length',2420)
	call strings_add_new('cbms vsm Hcanopy',2501)
	call strings_add_new('cbms vsm Growth',2502)
	call strings_add_new('cbms vsm Lim_Nitrogen',2503)
	call strings_add_new('cbms vsm Lim_Phosphorus',2504)
	call strings_add_new('cbms vsm Lim_Salinity',2505)
	call strings_add_new('cbms vsm Lim_Inundation',2506)
	call strings_add_new('cbms vsm Lim_Light',2507)
	call strings_add_new('cbms vsm BM_leaf',2508)
	call strings_add_new('cbms vsm BM_stem',2509)
	call strings_add_new('cbms vsm BM_root',2510)
	call strings_add_new('cbms vsm dBM_dt_Growth_leaf',2511)
	call strings_add_new('cbms vsm dBM_dt_Growth_stem',2512)
	call strings_add_new('cbms vsm dBM_dt_Growth_root',2513)
	call strings_add_new('cbms vsm dBM_dt_Mort_leaf',2550)
	call strings_add_new('cbms vsm dBM_dt_Mort_stem',2551)
	call strings_add_new('cbms vsm dBM_dt_Mort_root',2552)
	call strings_add_new('cbms vsm Mort_T_leaf',2553)
	call strings_add_new('cbms vsm Mort_T_stem',2554)
	call strings_add_new('cbms vsm Mort_T_root',2555)
	call strings_add_new('cbms vsm Respi_T_leaf',2556)
	call strings_add_new('cbms vsm Respi_T_stem',2557)
	call strings_add_new('cbms vsm Respi_T_root',2558)
	call strings_add_new('cbms vsm O2o Oxygen [mmol O2/m2]',2570)
	call strings_add_new('cbms vsm N1p Phosphate (PO4) [mmol P/m2]',2571)
	call strings_add_new('cbms vsm N4n Ammonium (NH4) [mmol N/m2]',2572)
	call strings_add_new('cbms vsm R1n Labile Dissolved Org. Mat. [mmol N/m2]',2573)
	call strings_add_new('cbms vsm R1c Labile Dissolved Org. Mat. [mg C/m2]',2574)
	call strings_add_new('cbms vsm R1p Labile Dissolved Org. Mat. [mmol P/m2]',2575)
	call strings_add_new('cbms vsm R6c Particulate Org. Mat. [mg C/m2]',2576)
	call strings_add_new('cbms vsm R6n Particulate Org. Mat. [mmol N/m2]',2577)
	call strings_add_new('cbms vsm R6p Particulate Org. Mat. [mmol P/m2]',2578)
	call strings_add_new('cbms vsm O3c Dissolved Inorganic Carbon [mg C/m2]',2579)
	call strings_add_new('cbms vsm Ben_N4n_Uptake',2601)
	call strings_add_new('cbms vsm Wat_N4n_Uptake',2602)
	call strings_add_new('cbms vsm Ben_R6n_Release',2603)
	call strings_add_new('cbms vsm Ben_R1n_Release',2604)
	call strings_add_new('cbms vsm Ben_N1p_Uptake',2605)
	call strings_add_new('cbms vsm Wat_N1p_Uptake',2606)
	call strings_add_new('cbms vsm Ben_R6p_Release',2607)
	call strings_add_new('cbms vsm Ben_R1p_Release',2608)
	call strings_add_new('cbms vsm Wat_R6c_Release',2609)
	call strings_add_new('cbms vsm Ben_R1c_Release',2610)
	call strings_add_new('cbms vsm Wat_R1c_Release',2611)
	call strings_add_new('cbms vsm Ben_R6c_Release',2612)
	call strings_add_new('cbms vsm Wat_O3c_Release',2613)
	call strings_add_new('cbms vsm Wat_O3c_Photosynt',2614)
	call strings_add_new('cbms vsm Ben_O2o_OxyDem',2615)
	call strings_add_new('cbms vsm Wat_O2o_OxyDem',2616)
	call strings_add_new('cbms vsm Wat_O2o_Photosynt',2617)

	call strings_set_short(1001,'cbmsbfm_O2o')
	call strings_set_short(1002,'cbmsbfm_N1p')
	call strings_set_short(1003,'cbmsbfm_N3n')
	call strings_set_short(1004,'cbmsbfm_N4n')
	call strings_set_short(1005,'cbmsbfm_O4n')
	call strings_set_short(1006,'cbmsbfm_N5s')
	call strings_set_short(1007,'cbmsbfm_N6r')
	call strings_set_short(1008,'cbmsbfm_B1c')
	call strings_set_short(1009,'cbmsbfm_B1n')
	call strings_set_short(1010,'cbmsbfm_B1p')
	call strings_set_short(1011,'cbmsbfm_P1c')
	call strings_set_short(1012,'cbmsbfm_P1n')
	call strings_set_short(1013,'cbmsbfm_P1p')
	call strings_set_short(1014,'cbmsbfm_P1l')
	call strings_set_short(1015,'cbmsbfm_P1s')
	call strings_set_short(1016,'cbmsbfm_P2c')
	call strings_set_short(1017,'cbmsbfm_P2n')
	call strings_set_short(1018,'cbmsbfm_P2p')
	call strings_set_short(1019,'cbmsbfm_P2l')
	call strings_set_short(1020,'cbmsbfm_P3c')
	call strings_set_short(1021,'cbmsbfm_P3n')
	call strings_set_short(1022,'cbmsbfm_P3p')
	call strings_set_short(1023,'cbmsbfm_P3l')
	call strings_set_short(1024,'cbmsbfm_P4c')
	call strings_set_short(1025,'cbmsbfm_P4n')
	call strings_set_short(1026,'cbmsbfm_P4p')
	call strings_set_short(1027,'cbmsbfm_P4l')
	call strings_set_short(1028,'cbmsbfm_Z3c')
	call strings_set_short(1029,'cbmsbfm_Z3n')
	call strings_set_short(1030,'cbmsbfm_Z3p')
	call strings_set_short(1031,'cbmsbfm_Z4c')
	call strings_set_short(1032,'cbmsbfm_Z4n')
	call strings_set_short(1033,'cbmsbfm_Z4p')
	call strings_set_short(1034,'cbmsbfm_Z5c')
	call strings_set_short(1035,'cbmsbfm_Z5n')
	call strings_set_short(1036,'cbmsbfm_Z5p')
	call strings_set_short(1037,'cbmsbfm_Z6c')
	call strings_set_short(1038,'cbmsbfm_Z6n')
	call strings_set_short(1039,'cbmsbfm_Z6p')
	call strings_set_short(1040,'cbmsbfm_R1c')
	call strings_set_short(1041,'cbmsbfm_R1n')
	call strings_set_short(1042,'cbmsbfm_R1p')
	call strings_set_short(1043,'cbmsbfm_R1l')
	call strings_set_short(1044,'cbmsbfm_R2c')
	call strings_set_short(1045,'cbmsbfm_R2l')
	call strings_set_short(1046,'cbmsbfm_R3c')
	call strings_set_short(1047,'cbmsbfm_R3l')
	call strings_set_short(1048,'cbmsbfm_R6c')
	call strings_set_short(1049,'cbmsbfm_R6n')
	call strings_set_short(1050,'cbmsbfm_R6p')
	call strings_set_short(1051,'cbmsbfm_R6s')
	call strings_set_short(1052,'cbmsbfm_O3c')
	call strings_set_short(1053,'cbmsbfm_O3h')
	call strings_set_short(1054,'cbmsbfm_O5c')
	call strings_set_short(1151,'cbmsbfm_ppqpcPPY_iiP1')
	call strings_set_short(1152,'cbmsbfm_ppqpcPPY_iiP2')
	call strings_set_short(1153,'cbmsbfm_ppqpcPPY_iiP3')
	call strings_set_short(1154,'cbmsbfm_ppqpcPPY_iiP4')
	call strings_set_short(1155,'cbmsbfm_ppqncPPY_iiP1')
	call strings_set_short(1156,'cbmsbfm_ppqncPPY_iiP2')
	call strings_set_short(1157,'cbmsbfm_ppqncPPY_iiP3')
	call strings_set_short(1158,'cbmsbfm_ppqncPPY_iiP4')
	call strings_set_short(1159,'cbmsbfm_ppqscPPY_iiP1')
	call strings_set_short(1160,'cbmsbfm_ppeiPPY_iiP1')
	call strings_set_short(1161,'cbmsbfm_ppeiPPY_iiP2')
	call strings_set_short(1162,'cbmsbfm_ppeiPPY_iiP3')
	call strings_set_short(1163,'cbmsbfm_ppeiPPY_iiP4')
	call strings_set_short(1164,'cbmsbfm_ppuc_iiP1')
	call strings_set_short(1165,'cbmsbfm_ppuc_iiP2')
	call strings_set_short(1166,'cbmsbfm_ppuc_iiP3')
	call strings_set_short(1167,'cbmsbfm_ppuc_iiP4')
	call strings_set_short(1168,'cbmsbfm_ppun_iiP1')
	call strings_set_short(1169,'cbmsbfm_ppun_iiP2')
	call strings_set_short(1170,'cbmsbfm_ppun_iiP3')
	call strings_set_short(1171,'cbmsbfm_ppun_iiP4')
	call strings_set_short(1172,'cbmsbfm_ppup_iiP1')
	call strings_set_short(1173,'cbmsbfm_ppup_iiP2')
	call strings_set_short(1174,'cbmsbfm_ppup_iiP3')
	call strings_set_short(1175,'cbmsbfm_ppup_iiP4')
	call strings_set_short(1176,'cbmsbfm_ppETW')
	call strings_set_short(1177,'cbmsbfm_ppESW')
	call strings_set_short(1178,'cbmsbfm_ppERHO')
	call strings_set_short(1179,'cbmsbfm_ppPAR_phyto1')
	call strings_set_short(1180,'cbmsbfm_ppruPPYc')
	call strings_set_short(1181,'cbmsbfm_ppresPPYc')
	call strings_set_short(1182,'cbmsbfm_ppruZOOc')
	call strings_set_short(1183,'cbmsbfm_ppremPBAn')
	call strings_set_short(1184,'cbmsbfm_ppremPBAp')
	call strings_set_short(1185,'cbmsbfm_ppremPOC')
	call strings_set_short(1186,'cbmsbfm_pppH')
	call strings_set_short(1187,'cbmsbfm_ppruPBAc')
	call strings_set_short(1188,'cbmsbfm_ppruMEZ1c')
	call strings_set_short(1189,'cbmsbfm_ppruMEZ2c')
	call strings_set_short(1190,'cbmsbfm_ppruMIZ1c')
	call strings_set_short(1191,'cbmsbfm_ppruMIZ2c')
	call strings_set_short(1301,'cbmsben_O2o')
	call strings_set_short(1302,'cbmsben_N1p')
	call strings_set_short(1303,'cbmsben_N3n')
	call strings_set_short(1304,'cbmsben_N4n')
	call strings_set_short(1305,'cbmsben_N5s')
	call strings_set_short(1306,'cbmsben_O3c')
	call strings_set_short(1307,'cbmsben_R6c')
	call strings_set_short(1308,'cbmsben_R6n')
	call strings_set_short(1309,'cbmsben_R6p')
	call strings_set_short(1310,'cbmsben_R6s')
	call strings_set_short(1311,'cbmsben_R1c')
	call strings_set_short(1312,'cbmsben_R1n')
	call strings_set_short(1313,'cbmsben_R1p')
	call strings_set_short(1401,'cbmsfben_diffu_O2o')
	call strings_set_short(1402,'cbmsfben_diffu_N1p')
	call strings_set_short(1403,'cbmsfben_diffu_N3n')
	call strings_set_short(1404,'cbmsfben_diffu_N4n')
	call strings_set_short(1405,'cbmsfben_diffu_N5s')
	call strings_set_short(1406,'cbmsfben_diffu_O3c')
	call strings_set_short(1407,'cbmsfben_diffu_R6c')
	call strings_set_short(1408,'cbmsfben_diffu_R6n')
	call strings_set_short(1409,'cbmsfben_diffu_R6p')
	call strings_set_short(1410,'cbmsfben_diffu_R6s')
	call strings_set_short(1411,'cbmsfben_diffu_R1c')
	call strings_set_short(1412,'cbmsfben_diffu_R1n')
	call strings_set_short(1413,'cbmsfben_diffu_R1p')
	call strings_set_short(1501,'cbmsfben_remin_O2o')
	call strings_set_short(1502,'cbmsfben_remin_N1p')
	call strings_set_short(1503,'cbmsfben_remin_N3n')
	call strings_set_short(1504,'cbmsfben_remin_N4n')
	call strings_set_short(1505,'cbmsfben_remin_N5s')
	call strings_set_short(1506,'cbmsfben_remin_O3c')
	call strings_set_short(1507,'cbmsfben_remin_R6c')
	call strings_set_short(1508,'cbmsfben_remin_R6n')
	call strings_set_short(1509,'cbmsfben_remin_R6p')
	call strings_set_short(1510,'cbmsfben_remin_R6s')
	call strings_set_short(1511,'cbmsfben_remin_R1c')
	call strings_set_short(1512,'cbmsfben_remin_R1n')
	call strings_set_short(1513,'cbmsfben_remin_R1p')
	call strings_set_short(1601,'cbmsfben_nitri_O2o')
	call strings_set_short(1602,'cbmsfben_nitri_N1p')
	call strings_set_short(1603,'cbmsfben_nitri_N3n')
	call strings_set_short(1604,'cbmsfben_nitri_N4n')
	call strings_set_short(1605,'cbmsfben_nitri_N5s')
	call strings_set_short(1606,'cbmsfben_nitri_O3c')
	call strings_set_short(1607,'cbmsfben_nitri_R6c')
	call strings_set_short(1608,'cbmsfben_nitri_R6n')
	call strings_set_short(1609,'cbmsfben_nitri_R6p')
	call strings_set_short(1610,'cbmsfben_nitri_R6s')
	call strings_set_short(1611,'cbmsfben_nitri_R1c')
	call strings_set_short(1612,'cbmsfben_nitri_R1n')
	call strings_set_short(1613,'cbmsfben_nitri_R1p')
	call strings_set_short(1701,'cbmsfben_denit_O2o')
	call strings_set_short(1702,'cbmsfben_denit_N1p')
	call strings_set_short(1703,'cbmsfben_denit_N3n')
	call strings_set_short(1704,'cbmsfben_denit_N4n')
	call strings_set_short(1705,'cbmsfben_denit_N5s')
	call strings_set_short(1706,'cbmsfben_denit_O3c')
	call strings_set_short(1707,'cbmsfben_denit_R6c')
	call strings_set_short(1708,'cbmsfben_denit_R6n')
	call strings_set_short(1709,'cbmsfben_denit_R6p')
	call strings_set_short(1710,'cbmsfben_denit_R6s')
	call strings_set_short(1711,'cbmsfben_denit_R1c')
	call strings_set_short(1712,'cbmsfben_denit_R1n')
	call strings_set_short(1713,'cbmsfben_denit_R1p')
	call strings_set_short(1801,'cbmsfwatben_diffu_O2o')
	call strings_set_short(1802,'cbmsfwatben_diffu_N1p')
	call strings_set_short(1803,'cbmsfwatben_diffu_N3n')
	call strings_set_short(1804,'cbmsfwatben_diffu_N4n')
	call strings_set_short(1805,'cbmsfwatben_diffu_N5s')
	call strings_set_short(1806,'cbmsfwatben_diffu_O3c')
	call strings_set_short(1807,'cbmsfwatben_diffu_R6c')
	call strings_set_short(1808,'cbmsfwatben_diffu_R6n')
	call strings_set_short(1809,'cbmsfwatben_diffu_R6p')
	call strings_set_short(1810,'cbmsfwatben_diffu_R6s')
	call strings_set_short(1811,'cbmsfwatben_diffu_R1c')
	call strings_set_short(1812,'cbmsfwatben_diffu_R1n')
	call strings_set_short(1813,'cbmsfwatben_diffu_R1p')
	call strings_set_short(1901,'cbmsfwatben_depos_O2o')
	call strings_set_short(1902,'cbmsfwatben_depos_N1p')
	call strings_set_short(1903,'cbmsfwatben_depos_N3n')
	call strings_set_short(1904,'cbmsfwatben_depos_N4n')
	call strings_set_short(1905,'cbmsfwatben_depos_N5s')
	call strings_set_short(1906,'cbmsfwatben_depos_O3c')
	call strings_set_short(1907,'cbmsfwatben_depos_R6c')
	call strings_set_short(1908,'cbmsfwatben_depos_R6n')
	call strings_set_short(1909,'cbmsfwatben_depos_R6p')
	call strings_set_short(1910,'cbmsfwatben_depos_R6s')
	call strings_set_short(1911,'cbmsfwatben_depos_R1c')
	call strings_set_short(1912,'cbmsfwatben_depos_R1n')
	call strings_set_short(1913,'cbmsfwatben_depos_R1p')
	call strings_set_short(2001,'cbmsfwatben_resus_O2o')
	call strings_set_short(2002,'cbmsfwatben_resus_N1p')
	call strings_set_short(2003,'cbmsfwatben_resus_N3n')
	call strings_set_short(2004,'cbmsfwatben_resus_N4n')
	call strings_set_short(2005,'cbmsfwatben_resus_N5s')
	call strings_set_short(2006,'cbmsfwatben_resus_O3c')
	call strings_set_short(2007,'cbmsfwatben_resus_R6c')
	call strings_set_short(2008,'cbmsfwatben_resus_R6n')
	call strings_set_short(2009,'cbmsfwatben_resus_R6p')
	call strings_set_short(2010,'cbmsfwatben_resus_R6s')
	call strings_set_short(2011,'cbmsfwatben_resus_R1c')
	call strings_set_short(2012,'cbmsfwatben_resus_R1n')
	call strings_set_short(2013,'cbmsfwatben_resus_R1p')
	call strings_set_short(2101,'cbmsfwatben_erros_O2o')
	call strings_set_short(2102,'cbmsfwatben_erros_N1p')
	call strings_set_short(2103,'cbmsfwatben_erros_N3n')
	call strings_set_short(2104,'cbmsfwatben_erros_N4n')
	call strings_set_short(2105,'cbmsfwatben_erros_N5s')
	call strings_set_short(2106,'cbmsfwatben_erros_O3c')
	call strings_set_short(2107,'cbmsfwatben_erros_R6c')
	call strings_set_short(2108,'cbmsfwatben_erros_R6n')
	call strings_set_short(2109,'cbmsfwatben_erros_R6p')
	call strings_set_short(2110,'cbmsfwatben_erros_R6s')
	call strings_set_short(2111,'cbmsfwatben_erros_R1c')
	call strings_set_short(2112,'cbmsfwatben_erros_R1n')
	call strings_set_short(2113,'cbmsfwatben_erros_R1p')
	call strings_set_short(2201,'cbmsvma_BM')
	call strings_set_short(2202,'cbmsvma_Hcanopy')
	call strings_set_short(2203,'cbmsvma_dBM_dt_Growth')
	call strings_set_short(2204,'cbmsvma_dBM_dt_Mort')
	call strings_set_short(2205,'cbmsvma_Growth')
	call strings_set_short(2206,'cbmsvma_Mortality')
	call strings_set_short(2207,'cbmsvma_Lim_Nitrogen')
	call strings_set_short(2208,'cbmsvma_Lim_Phosphorus')
	call strings_set_short(2209,'cbmsvma_Lim_Salinity')
	call strings_set_short(2210,'cbmsvma_Lim_Temperature')
	call strings_set_short(2211,'cbmsvma_Lim_Light')
	call strings_set_short(2212,'cbmsvma_QN')
	call strings_set_short(2213,'cbmsvma_QP')
	call strings_set_short(2250,'cbmsvma_O2o')
	call strings_set_short(2251,'cbmsvma_N1p')
	call strings_set_short(2252,'cbmsvma_N3n')
	call strings_set_short(2253,'cbmsvma_N4n')
	call strings_set_short(2254,'cbmsvma_R1n')
	call strings_set_short(2255,'cbmsvma_R1c')
	call strings_set_short(2256,'cbmsvma_R1p')
	call strings_set_short(2257,'cbmsvma_R6c')
	call strings_set_short(2258,'cbmsvma_R6n')
	call strings_set_short(2259,'cbmsvma_R6p')
	call strings_set_short(2260,'cbmsvma_O3c')
	call strings_set_short(2301,'cbmsfvma_Wat_N4n_Uptake')
	call strings_set_short(2302,'cbmsfvma_Wat_N3n_Uptake')
	call strings_set_short(2303,'cbmsfvma_Wat_R6n_Release')
	call strings_set_short(2304,'cbmsfvma_Wat_R1n_Release')
	call strings_set_short(2305,'cbmsfvma_Wat_N3n_Release')
	call strings_set_short(2306,'cbmsfvma_Wat_N4n_Release')
	call strings_set_short(2307,'cbmsfvma_Wat_N1p_Uptake')
	call strings_set_short(2308,'cbmsfvma_Wat_N1p_Release')
	call strings_set_short(2309,'cbmsfvma_Wat_R6p_Release')
	call strings_set_short(2310,'cbmsfvma_Wat_R1p_Release')
	call strings_set_short(2311,'cbmsfvma_Wat_O2o_Photosy')
	call strings_set_short(2312,'cbmsfvma_Wat_O2o_Resp')
	call strings_set_short(2313,'cbmsfvma_Wat_O3c_Uptake')
	call strings_set_short(2314,'cbmsfvma_Wat_O3c_Release')
	call strings_set_short(2315,'cbmsfvma_Wat_R6c_Release')
	call strings_set_short(2316,'cbmsfvma_Wat_R1c_Release')
	call strings_set_short(2401,'cbmswat_temp')
	call strings_set_short(2402,'cbmswat_salt')
	call strings_set_short(2403,'cbmswat_density')
	call strings_set_short(2404,'cbmswat_ph')
	call strings_set_short(2405,'cbmswat_viscosity')
	call strings_set_short(2406,'cbmswat_volume')
	call strings_set_short(2407,'cbmswat_area')
	call strings_set_short(2408,'cbmswat_dZ')
	call strings_set_short(2409,'cbmswat_light')
	call strings_set_short(2410,'cbmswat_PAR')
	call strings_set_short(2411,'cbmswat_solrad')
	call strings_set_short(2412,'cbmswat_airtemp')
	call strings_set_short(2413,'cbmswat_ssh')
	call strings_set_short(2414,'cbmswat_tau')
	call strings_set_short(2415,'cbmswat_wind')
	call strings_set_short(2416,'cbmswat_H_water_column')
	call strings_set_short(2417,'cbmswat_bott_temp')
	call strings_set_short(2418,'cbmswat_ice')
	call strings_set_short(2419,'cbmswat_CO2air')
	call strings_set_short(2420,'cbmswat_photoperiod')
	call strings_set_short(2501,'cbmsvsm_Hcanopy')
	call strings_set_short(2502,'cbmsvsm_Growth')
	call strings_set_short(2503,'cbmsvsm_Lim_Nitrogen')
	call strings_set_short(2504,'cbmsvsm_Lim_Phosphorus')
	call strings_set_short(2505,'cbmsvsm_Lim_Salinity')
	call strings_set_short(2506,'cbmsvsm_Lim_Inundation')
	call strings_set_short(2507,'cbmsvsm_Lim_Light')
	call strings_set_short(2508,'cbmsvsm_BM_leaf')
	call strings_set_short(2509,'cbmsvsm_BM_stem')
	call strings_set_short(2510,'cbmsvsm_BM_root')
	call strings_set_short(2511,'cbmsvsm_dBM_dt_Growth_le')
	call strings_set_short(2512,'cbmsvsm_dBM_dt_Growth_st')
	call strings_set_short(2513,'cbmsvsm_dBM_dt_Growth_ro')
	call strings_set_short(2550,'cbmsvsm_dBM_dt_Mort_leaf')
	call strings_set_short(2551,'cbmsvsm_dBM_dt_Mort_stem')
	call strings_set_short(2552,'cbmsvsm_dBM_dt_Mort_root')
	call strings_set_short(2553,'cbmsvsm_Mort_T_leaf')
	call strings_set_short(2554,'cbmsvsm_Mort_T_stem')
	call strings_set_short(2555,'cbmsvsm_Mort_T_root')
	call strings_set_short(2556,'cbmsvsm_Respi_T_leaf')
	call strings_set_short(2557,'cbmsvsm_Respi_T_stem')
	call strings_set_short(2558,'cbmsvsm_Respi_T_root')
	call strings_set_short(2570,'cbmsvsm_O2o')
	call strings_set_short(2571,'cbmsvsm_N1p')
	call strings_set_short(2572,'cbmsvsm_N4n')
	call strings_set_short(2573,'cbmsvsm_R1n')
	call strings_set_short(2574,'cbmsvsm_R1c')
	call strings_set_short(2575,'cbmsvsm_R1p')
	call strings_set_short(2576,'cbmsvsm_R6c')
	call strings_set_short(2577,'cbmsvsm_R6n')
	call strings_set_short(2578,'cbmsvsm_R6p')
	call strings_set_short(2579,'cbmsvsm_O3c')
	call strings_set_short(2601,'cbmsfvsm_Ben_N4n_Uptake')
	call strings_set_short(2602,'cbmsfvsm_Wat_N4n_Uptake')
	call strings_set_short(2603,'cbmsfvsm_Ben_R6n_Release')
	call strings_set_short(2604,'cbmsfvsm_Ben_R1n_Release')
	call strings_set_short(2605,'cbmsfvsm_Ben_N1p_Uptake')
	call strings_set_short(2606,'cbmsfvsm_Wat_N1p_Uptake')
	call strings_set_short(2607,'cbmsfvsm_Ben_R6p_Release')
	call strings_set_short(2608,'cbmsfvsm_Ben_R1p_Release')
	call strings_set_short(2609,'cbmsfvsm_Wat_R6c_Release')
	call strings_set_short(2610,'cbmsfvsm_Ben_R1c_Release')
	call strings_set_short(2611,'cbmsfvsm_Wat_R1c_Release')
	call strings_set_short(2612,'cbmsfvsm_Ben_R6c_Release')
	call strings_set_short(2613,'cbmsfvsm_Wat_O3c_Release')
	call strings_set_short(2614,'cbmsfvsm_Wat_O3c_Photosy')
	call strings_set_short(2615,'cbmsfvsm_Ben_O2o_OxyDem')
	call strings_set_short(2616,'cbmsfvsm_Wat_O2o_OxyDem')
	call strings_set_short(2617,'cbmsfvsm_Wat_O2o_Photosy')

 	end subroutine

