#!/bin/sh
#
#---------------------------------------------------------

what=$1

echo "SHYFEM_HOME = $SHYFEM_HOME"
file=strings_$what.f90

date=$( date +%d.%m.%Y )
d1="!--------------------------------------------------------------------------"
d2="!****************************************************************"

echo ""					>  header.tmp
echo "$d1"				>> header.tmp
cat copy.txt				>> header.tmp
echo "$d1"				>> header.tmp

echo ""					>> header.tmp
echo "! $what strings"			>> header.tmp
echo "!"				>> header.tmp
echo "! revision log :"			>> header.tmp
echo "!"				>> header.tmp
echo "! $date	ggu&clc	automatically generated by bfm.sh"	>> header.tmp
echo ""					>> header.tmp
echo "$d2"				>> header.tmp

#---------------------------------------------------------

cat header.tmp $file 			> tmp.tmp
echo "$d2"				>> tmp.tmp
echo ""					>> tmp.tmp

#---------------------------------------------------------

